<div class="intro">
<p>This example shows how to use advanced test options, which allow you to specify additional information about how a test should be run.
  Each <a href="index.html#testcase"><code>TestCase</code></a> can specify up to three different options for tests,
  including tests that should be ignored, tests that should throw an error, and tests that should fail.</p>
</div>

<div class="example yui3-skin-sam">
    {{>test-advanced-test-options-source}}
</div>

<h2 class="first">Advanced Test Options</h2>

<p>This example begins by creating a namespace and a <code>Y.Test.Case</code> object:</p>
```
Y.namespace("example.test");
Y.example.test.AdvancedOptionsTestCase = new Y.TestCase({
    name: "Advanced Options Tests"
});
```

<p>This <code>Y.Test.Case</code> serves as the basis for this example.</p>

<h3>Using <code>_should</code></h3>

<p>Immediately after the <code>name</code> of the <code>Y.Test.Case</code> is defined, there is a <code>_should</code> property.
  This property specifies information about how tests <em>should</em> behave and is defined as an object literal with one
  or more of the following properties: <code>fail</code>, <code>error</code>, and <code>ignore</code>.Each of these three
  is also defined as an object literal whose property names map directly to the names of test methods in the <code>Y.Test.Case</code>.
  This example uses all three properties:</p>
```
Y.example.test.AdvancedOptionsTestCase = new Y.TestCase({

    //the name of the test case - if not provided, one is automatically generated
    name: "Advanced Options Tests",

    /*
     * Specifies tests that "should" be doing something other than the expected.
     */
    _should: {

        /*
         * Tests listed in here should fail, meaning that if they fail, the test
         * has passed. This is used mostly for YuiTest to test itself, but may
         * be helpful in other cases.
         */
        fail: {

            //the test named "testFail" should fail
            testFail: true

        },

        /*
         * Tests listed here should throw an error of some sort. If they throw an
         * error, then they are considered to have passed.
         */
        error: {

            /*
             * You can specify "true" for each test, in which case any error will
             * cause the test to pass.
             */
            testGenericError: true,

            /*
             * You can specify an error message, in which case the test passes only
             * if the error thrown matches the given message.
             */
            testStringError: "I'm a specific error message.",
            testStringError2: "I'm a specific error message.",

            /*
             * You can also specify an error object, in which case the test passes only
             * if the error thrown is on the same type and has the same message.
             */
            testObjectError: new TypeError("Number expected."),
            testObjectError2: new TypeError("Number expected."),
            testObjectError3: new TypeError("Number expected.")

        },

        /*
         * Tests listed here should be ignored when the test case is run. For these tests,
         * setUp() and tearDown() are not called.
         */
        ignore : {

            testIgnore: true

        }
    },

    ...
});
```

<p>This <code>Y.Test.Case</code> specifies one test that should fail, six that should throw an error, and one that should be ignored.</p>
<p>In the <code>fail</code> section, the test method <code>testFail()</code> is specified as one that should fail. By adding the
  property <code>testFail</code> and settings its value to true, the <code>Y.Test.Runner</code> knows that this test is expected to fail.
  If the test were to be run without failing, it would be considered a failure of the test. This feature is useful when testing
  YUI Test itself or addon components to YUI Test.</p>
<p>Moving on to the <code>error</code> section, there are six tests specified that should throw an error. There are three different ways
  to indicate that a test is expected to throw an error. The first is simply to add a property with the same name as the test method
  and set its value equal to true (similar to specifying tests that should fail). In this example, the <code>testGenericError()</code>
  method is specified this way. When specified like this, the test passes regardless of the type of error that occurs. This can be
  dangerous since unexpected errors will also cause the test to pass. To be more specific, set the property value for the test method
  to an error message string. When a string is used instead of the Boolean true, the test passes only when an error is thrown and that
  error message matches the string. In this example, <code>testStringError()</code> and <code>testStringError2()</code> expect an error
  to be thrown with an error message of &quot;I'm a specific error message.&quot; If any other error occurs inside of the these methods,
  the test will fail because the error message doesn't match. The last way to specify an error should occur is to create an actual error
  object, which is the case with <code>testObjectError()</code>, <code>testObjectError2()</code>, and <code>testObjectError3()</code>.
  When specified in this way, a test will pass only when an error is thrown whose constructor and error message match that of the
  error object.</p>
<p>The last section is <code>ignore</code>, which determines tests that should be ignored. In this example, the method <code>testIgnore()</code>
  is set to be ignored when the <code>Y.Test.Case</code> is executed. Test in the <code>ignore</code> section are specified the same way
  as those in the <code>fail</code> section, by adding the name as a property and setting its value to true.</p>

<h3>Creating the test methods</h3>

<p>The next part of the example contains the actual test methods. Since each test method is specified as having a certain behavior in
  <code>_should</code>, they each do something to show their particular functionality.</p>
<p>The first method is <code>testFail()</code>, which does nothing but purposely fail. Since this method is specified as one that should
  fail, it means that this test will pass:</p>
```
Y.example.test.AdvancedOptionsTestCase = new Y.Test.Case({

    //the name of the test case - if not provided, one is automatically generated
    name: "Advanced Options Tests",

    ...

    testFail : function() {

        //force a failure - but since this test "should" fail, it will pass
        Y.Assert.fail("Something bad happened.");

    },

    ...
});
```
<p>This method uses <code>Assert.fail()</code> to force the test to fail. This type of method is helpful if you are creating your own
  type of assert methods that should fail when certain data is passed in.</p>
<p>Next, the test methods that should error are defined.  The <code>testGenericError()</code> method is specified as needing to throw
  an error to pass. In the <code>error</code> section, <code>testGenericError</code> is set to true, meaning that any error causes
  this method to pass. To illustrate this, the method simply throws an error:</p>
```
Y.example.test.AdvancedOptionsTestCase = new Y.Test.Case({

    //the name of the test case - if not provided, one is automatically generated
    name: "Advanced Options Tests",

    ...

    testGenericError : function() {
        throw new Error("Generic error");
    },

    ...
});
```
<p>The fact that this method throws an error is enough to cause it to pass (the type of error and error message don't matter). The next
  two methods, <code>testStringError()</code> and <code>testStringError2()</code> are specified as throwing an error with a specific
  message (&quot;I'm a specific error message.&quot;):</p>
```
Y.example.test.AdvancedOptionsTestCase = new Y.Test.Case({

    //the name of the test case - if not provided, one is automatically generated
    name: "Advanced Options Tests",

    ...

    testStringError : function() {

        //throw a specific error message - this will pass because it "should" happen
        throw new Error("I'm a specific error message.");
    },

    testStringError2 : function() {

        //throw a specific error message - this will fail because the message isn't expected
        throw new Error("I'm a specific error message, but a wrong one.");
    },

    ...
});
```
<p>The <code>testStringError()</code> method will pass when executed because the error message matches up exactly with the one
  specified in the <code>error</code> section. The <code>testStringError2()</code> method, however, will fail because its
  error message is different from the one specified.</p>
<p>To be more specific, <code>testObjectError()</code>, <code>testObjectError2()</code>, and <code>testObjectError3()</code>,
  specified an error type (<code>TypeError</code>) and an error messsage (&quot;Number expected.&quot;):</p>
```
Y.example.test.AdvancedOptionsTestCase = new Y.Test.Case({

    //the name of the test case - if not provided, one is automatically generated
    name: "Advanced Options Tests",

    ...

    testObjectError : function() {

        //throw a specific error and message - this will pass because it "should" happen
        throw new TypeError("Number expected.");
    },

    testObjectError2 : function() {

        //throw a specific error and message - this will fail because the type doesn't match
        throw new Error("Number expected.");
    },

    testObjectError3 : function() {

        //throw a specific error and message - this will fail because the message doesn't match
        throw new TypeError("String expected.");
    },

    ...
});
```
<p>Of the these three methods, only <code>testObjectError()</code> will pass because it's the only one that throws a <code>TypeError</code>
  object with the message, &quot;Number expected.&quot; The <code>testObjectError2()</code> method will fail because the type of error
  being thrown (<code>Error</code>) is different from the expected type (<code>TypeError</code>), as specified in the <code>error</code>
  section. The last method, <code>testObjectError3()</code>, also fails. Though it throws the right type of error, the error message
  doesn't match the one that was specified.</p>
<p>The last method in the <code>Y.Test.Case</code> is <code>testIgnore()</code>, which is specified to be ignored. To be certain, this
  method pops up a message:</p>
```
Y.example.test.AdvancedOptionsTestCase = new Y.Test.Case({

    //the name of the test case - if not provided, one is automatically generated
    name: "Advanced Options Tests",

    ...

    testIgnore : function () {
        alert("You'll never see this.");
    }
});
```
<p>If this test weren't ignored, then the alert should be displayed. Since it is ignored, though, you will never see the alert. Additionally,
  there is a special message displayed in the <code>Y.Console</code> when a test is ignored.</p>

<h3>Running the tests</h3>

<p>With all of the tests defined, the last step is to run them:</p>

```
//create the console
(new Y.Test.Console({
    verbose : true,
    newestOnTop : false
})).render('#testLogger');

//add the test suite to the runner's queue
Y.Test.Runner.add(Y.example.test.AdvancedOptionsTestCase);

//run the tests
Y.Test.Runner.run();
```

<p>Before running the tests, it's necessary to create a <code>Y.Console</code> object to display the results (otherwise the tests would run
  but you wouldn't see the results). After that, the <code>Y.Test.Runner</code> is loaded with the <code>Y.Test.Suite</code> object by calling
  <code>add()</code> (any number of <code>Y.Test.Case</code> and <code>Y.Test.Suite</code> objects can be added to a <code>Y.Test.Runner</code>,
  this example only adds one for simplicity). The very last step is to call <code>run()</code>, which begins executing the tests in its
  queue and displays the results in the <code>Y.Console</code>.</p>

<h2>Complete Example Source</h2>

```
{{>test-advanced-test-options-source}}
```
